[package]
name = "doc_item"
version = "0.2.2"
authors = ["Anders Evensen"]
edition = "2018"
description = "Attributes for item-level documentation customization."
readme = "README.md"
repository = "https://github.com/Anders429/doc_item"
license = "MIT OR Apache-2.0"
keywords = ["documentation", "item", "info", "msrv", "nightly"]
categories = ["development-tools", "rust-patterns"]
exclude = [".github/", "ci/", "examples/"]

[lib]
proc-macro = true

[dependencies]
darling = "0.12.2"
once_cell = "1.7.2"
syn = {version="1.0.68", default-features=false, features=["derive", "parsing", "proc-macro"]}
