name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.50.0
    steps:
    - uses: actions/checkout@v2
    #- uses: browser-actions/setup-firefox@latest
    #- uses: browser-actions/setup-geckodriver@latest
    #- run: geckodriver --port=4444 --binary=/opt/hostedtoolcache/firefox/latest/x64/firefox &
    #- run: chromedriver --port=4444 --headless --disable-gpu --no-sandbox --disable-dev-shm-usage &
    #- run: chromedriver --
    - uses: nanasess/setup-chromedriver@master
    - name: Install latest Google Chrome
      run: wget -q https://script.install.devinsideyou.com/google-chrome && chmod +x google-chrome
    - run: chromedriver --port=4444 --headless --disable-gpu --no-sandbox --disable-dev-shm-usage &
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build docs
      working-directory: ./ci/frontend/test_target
      run: cargo doc
    - name: Run test
      working-directory: ./ci/frontend/doc_ui_test
      run: cargo run