name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.50.0
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@master
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub --port=4444 &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build docs
      working-directory: ./ci/frontend/test_target
      run: cargo doc
    - name: Run test
      working-directory: ./ci/frontend/doc_ui_test
      run: cargo run